[package]
name = "textlargetxt"
version = "0.1.0"
edition = "2021"

[dependencies]
memmap2 = "0.9.4"
rand = "0.8.5"
tokio = { version = "1.37.0", features = ["full"] }
[dev-dependencies]
criterion = "0.5.1"
